### ISSUE TITLE
SLOs cannot be created by terraform 

### ISSUE THREAD

**Issue by MKand** [GoogleCloudPlatform/reliable-app-platforms#29]
SLOs cannot be created by tf until atleast one SLO is created for the service via console. 
This is because the canonical service cannot be found by cloud monitoring. This appears to be a bug in CloudMonitoring.
    
Short-term fix: Run the deploy  pipeline with the flag _DEPLOY_SLO_ONLY set to *false* in the ci pipeline for the shop service. After all the services in shop are deployed, create an (any) SLO manually for the service in the ASM section of the GKE console. And rerun the deploy pipeline with _DEPLOY_SLO_ONLY set to *true* in the ci pipeline for each application.

A bug will be filed at CloudMonitoring

**Comment by stevemcghee** [comment]
it seems we need to use `custom` service now :(

https://leoy.blog/posts/define-gcp-managed-service-for-monitoring/

(blog post coming out soon)
