### ISSUE TITLE
GKE teardown with terraform destroy fails

### ISSUE THREAD

**Issue by MKand** [GoogleCloudPlatform/reliable-app-platforms#30]
When running the destruction pipeline (./build --terraform --destory), the GKE module fails at the end after the clusters are destroyed. This is because of a GKE hub "feature" that prevents destroy. 
Not sure which feature it is.

**Comment by stevemcghee** [comment]
On version 5.0.0+ of the provider, you must explicitly set deletion_protection = false and run terraform apply to write the field to state in order to destroy a cluster.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster

**Comment by stevemcghee** [comment]
i believe this is working now?
